<?php
  function comment_buddy_menu()
  {
    $items = array();
    $items['thanks'] = array(
      'title' => "Thank you!",
      'page callback' => 'thank_you',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function thank_you()
  {
    return '<p>Thank you for your submission. Please select a menu option above to continue browsing.</p>';
  }

  function comment_buddy_comment_publish()
  {
    $_GET['destination'] = 'thanks';
  }

  // function comment_buddy_comment_publish($comment)
  // {
  //   drupal_set_message(t("Thank you! Comment submitted!"));
  // }

  function comment_buddy_comment_update($comment)
  {
    drupal_set_message(t("Your comment has been changed."));
    search_touch_node($comment->nid);
  }

  function comment_buddy_comment_delete($comment)
  {
    drupal_set_message(t("Comment deleted. Good work eating your words."));
  }
