<?php

function user_greetings_menu() {
    $items = array();
    $items['splash'] = array(
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['splashout'] = array(
        'title' => 'Goodbye User!',
        'page callback' => 'say_goodbye',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function say_hello() {
  global $user;
  if (in_array('administrator',$user->roles)) {
    return '<p>Welcome to the Admin view!</p>';
  }
  elseif(in_array('authenticated',$user->roles)) {
    return '<p>Nice to see you!</p>';
  }
}

function say_goodbye() {
  // global $user;
  // if (in_array('administrator',$user->roles)) {
  //   return '<p>Bye bye bye!</p>';
  // }
  // elseif(in_array('authenticated',$user->roles)) {
    return '<p>Come back soon!</p>';
  // }
}

function user_greetings_user_login()
{
  $_GET['destination'] = 'splash';
}

function user_greetings_user_logout()
{
  $_GET['destination'] = 'splashout';
}
